apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "graphql-engine.fullname" . }}
  labels:
    {{- include "graphql-engine.labels" . | nindent 4 }}
data:
  HASURA_GRAPHQL_ENABLE_CONSOLE: {{ .Values.graphqlEnableConsole | quote }}
  HASURA_GRAPHQL_DEV_MODE: {{ .Values.graphqlDevMode | quote }}
