{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graphql-engine.fullname" . }}
  labels:
    {{- include "graphql-engine.labels" . | nindent 4 }}
type: Opaque
data:
  HASURA_GRAPHQL_DATABASE_URL: {{ .Values.graphqlDatabaseUrl | b64enc | quote }}
{{- end }}
