apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
data:
  INITIAL_MEMORY: {{ .Values.initialMemory | quote }}
  MAXIMUM_MEMORY: {{ .Values.maximumMemory | quote }}
  STABLE_EXTENSIONS: {{ .Values.stableExtensions | quote }}
  COMMUNITY_EXTENSIONS: {{ .Values.communityExtensions | quote }}
  GEOSERVER_CSRF_WHITELIST: {{ .Values.csrfWhitelist | quote }}
