{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mapserver.fullname" . }}
  labels:
    {{- include "mapserver.labels" . | nindent 4 }}
spec:
  accessModes:
{{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
