apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valtimo-console.fullname" . }}
  labels:
    {{- include "valtimo-console.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Values.config | toJson | nindent 4 }}
