apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
{{- end }}
