apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filter-proxy.fullname" . }}
  labels:
    {{- include "filter-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
