apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signalen-frontend-wcag.fullname" . }}
  labels:
    {{- include "signalen-frontend-wcag.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Values.config | toJson | indent 4 }}
  customDesignTokens.json: |-
{{ .Values.customDesignTokens | toJson | indent 4 }}
