apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "signals-frontend.fullname" . }}
  labels:
    {{- include "signals-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "signals-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.config | toJson | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "signals-frontend.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if ne (len .Values.command) 0 }}
          command: {{ toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if ne (len .Values.args) 0 }}
          args: {{ toYaml .Values.args | nindent 12 }}
          {{- end  }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app.json
              subPath: "app.json"
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
{{- if ne (len .Values.initContainers) 0 }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "signals-frontend.fullname" . }}
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
