apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valtimo-server.fullname" . }}
  labels:
    {{- include "valtimo-server.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_SECRET: {{ .Values.settings.keycloak.secret | toString | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.settings.database.password | toString | b64enc | quote }}
