apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signalen-gw.fullname" . }}
  labels:
    {{- include "signalen-gw.labels" . | nindent 4 }}
data:
  SIGNALEN_ENDPOINT: {{ .Values.settings.signalenEndpoint | quote }}
  SOURCE_NAME: {{ .Values.settings.sourceName | quote }}
