{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signalen-gw.fullname" . }}
  labels:
    {{- include "signalen-gw.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_TOKEN: {{ .Values.settings.jwtToken | b64enc | quote }}
{{- end }}
