apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.serviceName }}
  labels:
    {{- include "signals-frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "signals-frontend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
---
{{- if index .Values "signalen-wcag" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "signalen-wcag" "serviceName" }}
  labels:
    {{- include "signals-frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "signals-frontend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
{{ end }}
